# Managed Postgres for user state, on the Lakebase Autoscaling platform.
#
# Creating a project auto-provisions:
#   - a `production` branch
#   - a `primary` read-write endpoint on that branch
#
# Scale-to-zero is OFF by default on the auto-created endpoint. Autoscaling
# range and scale-to-zero are configured via the Postgres API or the Lakebase
# Autoscaling UI, not via the Database instance API. We do that as a one-time
# post-apply step — see docs/runbook.md.
#
# Resource is in Beta. Spec/status field names may change; pin a working
# provider version in versions.tf and re-verify on upgrades.
locals {
  production_branch_name     = "${databricks_postgres_project.main.name}/branches/production"
  production_endpoint_name   = "${local.production_branch_name}/endpoints/primary"
  postgres_database_name     = coalesce(var.postgres_database_name, replace(var.database_id, "-", "_"))
  databricks_cli_profile_arg = var.databricks_profile == "" ? "" : "--profile ${var.databricks_profile}"
}

resource "databricks_postgres_project" "main" {
  project_id = var.project_id

  spec = {
    pg_version   = var.pg_version
    display_name = var.display_name
  }
}

# ---------------------------------------------------------------------------
# Database role — provisioned first; owns the application database.
#
# Backed by the Databricks service principal (sp_application_id). Auth is
# LAKEBASE_OAUTH_V1, so no password exists — the SP presents a Databricks
# OAuth token when connecting. DATABRICKS_SUPERUSER membership covers all
# data-access privileges without separate GRANT statements.
#
# spec.attributes explicitly locks down the Postgres role attributes:
#   createdb   = false  — must not create new databases
#   createrole = false  — must not create other roles
#   bypassrls  = false  — must respect row-level security policies
# ---------------------------------------------------------------------------

resource "databricks_postgres_role" "main" {
  role_id = var.role_id
  parent  = local.production_branch_name

  spec = {
    identity_type    = "SERVICE_PRINCIPAL"
    postgres_role    = var.sp_application_id
    auth_method      = "LAKEBASE_OAUTH_V1"
    membership_roles = ["DATABRICKS_SUPERUSER"]

    attributes = {
      createdb   = false
      createrole = false
      bypassrls  = false
    }
  }
}

# ---------------------------------------------------------------------------
# Application database — owned by the role above.
# Terraform infers role → database ordering from spec.role, satisfying the
# Lakebase constraint of no parallel branch operations.
# ---------------------------------------------------------------------------

resource "databricks_postgres_database" "main" {
  database_id = var.database_id
  parent      = local.production_branch_name

  spec = {
    postgres_database = local.postgres_database_name
    role              = databricks_postgres_role.main.name
  }
}

# ---------------------------------------------------------------------------
# Schema migration — runs against the application database once it exists.
# Connects as the service principal (sp_application_id) using a short-lived
# Lakebase database credential generated by the Databricks CLI.
# Re-runs whenever schema.sql changes (filesha256 trigger).
# Requires: psql >=14, Databricks CLI, jq, DATABRICKS_HOST + auth configured.
# ---------------------------------------------------------------------------

resource "null_resource" "schema_migration" {
  triggers = {
    schema_hash   = filesha256("${path.module}/sql/schema.sql")
    database_name = local.postgres_database_name
  }

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = <<-EOT
      set -euo pipefail

      echo "==> Fetching endpoint host..."
      ENDPOINT_HOST=$(databricks ${local.databricks_cli_profile_arg} postgres list-endpoints \
        "${local.production_branch_name}" \
        --output json \
        | jq -r '.[] | select(.status.endpoint_type == "ENDPOINT_TYPE_READ_WRITE") | .status.hosts.host' \
        | head -1)

      if [ -z "$${ENDPOINT_HOST}" ]; then
        echo "ERROR: no read-write endpoint found. Is the production branch endpoint ACTIVE?"
        exit 1
      fi

      echo "==> Generating short-lived Lakebase database credential..."
      DATABASE_TOKEN=$(databricks ${local.databricks_cli_profile_arg} postgres generate-database-credential \
        "${local.production_endpoint_name}" \
        --output json \
        | jq -r '.token')

      [ -z "$${DATABASE_TOKEN}" ] || [ "$${DATABASE_TOKEN}" = "null" ] && { echo "ERROR: no Lakebase database token returned"; exit 1; }

      echo "==> Endpoint: $${ENDPOINT_HOST}"
      echo "==> Running migration against '${local.postgres_database_name}'..."

      PGPASSWORD="$${DATABASE_TOKEN}" psql \
        "postgresql://${var.sp_application_id}@$${ENDPOINT_HOST}/${local.postgres_database_name}?sslmode=require" \
        --file="${path.module}/sql/schema.sql" \
        --set ON_ERROR_STOP=on \
        --echo-errors

      echo "==> Migration complete."
    EOT
  }

  depends_on = [databricks_postgres_database.main]
}
